---
  - name: Configuration of NFS shares on the server machine
    hosts: all
    become: yes
    gather_facts: no
    tasks:
      - name: Install the NFS tools
        package:
          name: nfs-utils
          state: present
      
      - name: Generate a randomized name for the NFS share
        debug:
          msg: "{{ range(1,99) | random }}"
        register: nfs_suffix

      - name: Create the NFS read-write mountpoint
        file:
          path: /nfs{{nfs_suffix['msg']}}
          mode: '777'
          state: directory

      - name: Create the NFS read-only share mountpoint
        file:
          path: /nfs-ro{{nfs_suffix['msg']}}
          mode: '777'
          state: directory

      - name: Create the certificate share mountpoint
        file:
          path: /lab-certs
          mode: '777'
          state: directory

      - name: Create the /etc/exports file
        template:
          src: /vagrant/templates/exports.j2
          dest: /etc/exports

      - name: Open the firewall port 2049 for NFSv4
        firewalld:
          service: nfs
          permanent: yes
          immediate: yes
          state: enabled

      - name: Start the NFS service
        service:
          name: nfs-server
          enabled: yes
          state: restarted

      - name: Write the lab details to a file
        blockinfile:
          path: /home/vagrant/lab-config.txt
          create: yes
          block: |
            Summary of the NFS configuration:
              Random read-write share name: /nfs{{ nfs_suffix['msg'] }}
              Random read-only share name: /nfs-ro{{ nfs_suffix['msg'] }}

      - name: Display the location of the lab details
        debug:
          msg: Please check the configuration details of the lab in /home/vagrant/lab-config.txt on machine 'server'
          
