---
  - name: Configure an OpenLDAP server for excercises 
    hosts: all
    become: yes
    gather_facts: no
    tasks:
      - name: Install the server package and other tools
        package:
          name: 
            - openldap-servers
            - openldap-clients
          state: installed
      
      - name: Purge the old config directory
        shell: 
          cmd: rm -rf /etc/openldap/slapd.d/*

      - name: Purge the old data directory
        shell: 
          cmd: rm -rf /var/lib/ldap/*

      - name: Import the new configuration
        shell:
          cmd: /sbin/slapadd -n 0 -F /etc/openldap/slapd.d -l /vagrant/files/slapd-template.ldif

      - name: Change the config ownership to the LDAP user
        file:
          path: /etc/openldap/slapd.d
          owner: ldap
          group: ldap
          recurse: yes

      - name: Generate a private key for the LDAP server
        openssl_privatekey:
          path: /etc/openldap/certs/ldap_server.key
          state: present

      - name: Create a CSR for the LDAP server key
        openssl_csr:
          path: /etc/openldap/certs/ldap_server.csr
          privatekey_path: /etc/openldap/certs/ldap_server.key
          country_name: PL
          state_or_province_name: Slaskie
          locality_name: Katowice
          organization_name: Linux Lab
          common_name: server
          state: present

      - name: Issue the LDAP server certificate signed with the Lab CA key
        shell:
          cmd: openssl x509 -req -days 365 -CA /var/lib/ca/ca.crt -CAkey /var/lib/ca/ca.key -in /etc/openldap/certs/ldap_server.csr -out /etc/openldap/certs/ldap_server.crt

      - name: Copy the CA root certificate to the certificate directory of the LDAP server
        copy:
          src: /var/lib/ca/ca.crt
          dest: /etc/openldap/certs/ca.crt

      - name: Copy the CA root certificate to the NFS share /lab-certs
        copy:
          src: /var/lib/ca/ca.crt
          dest: /lab-certs/ca.crt

      - name: Change the certificate directory ownership to the LDAP user
        file:
          path: /etc/openldap/certs
          owner: ldap
          group: ldap
          recurse: yes

      - name: Enable and start the LDAP server
        service:
          name: slapd
          enabled: yes
          state: started

      - name: Create the organization
        shell:
          cmd: ldapadd -x -D 'cn=Manager,dc=example,dc=com' -w secret -f /vagrant/files/organization.ldif
      
      - name: Create the containers
        shell:
          cmd: ldapadd -x -D 'cn=Manager,dc=example,dc=com' -w secret -f /vagrant/files/containers.ldif

      - name: Create an LDAP user
        shell:
          cmd: ldapadd -x -D 'cn=Manager,dc=example,dc=com' -w secret -f /vagrant/files/ldapuser.ldif

      - name: Set the LDAP user's password
        shell:
          cmd: ldappasswd -s linux123 -D 'cn=Manager,dc=example,dc=com' -w secret -x 'uid=ldapuser,ou=users,dc=example,dc=com'

      - name: Open the firewall port 389 for LDAP
        firewalld:
          service: ldap
          permanent: yes
          immediate: yes
          state: enabled

